// Конфігурація таблиць для механізму імпорту "брудних" даних.
// Кожна ціль має: підпис, назву staging-таблиці, список raw_*-полів
// (саме вони заповнюються на етапі "stage" з мапінгу колонок файлу),
// та назву фінальної таблиці.

export const IMPORT_TABLES = {
  lsmd: {
    label: 'Госпіталізації (lsmd)',
    staging: 'lsmd_import_staging',
    target: 'lsmd',
    fields: [
      { key: 'raw_id_case', label: 'Номер випадку' },
      { key: 'raw_patient_name', label: 'ПІБ пацієнта' },
      { key: 'raw_gender', label: 'Стать' },
      { key: 'raw_age', label: 'Вік' },
      { key: 'raw_birth_date', label: 'Дата народження' },
      { key: 'raw_phone', label: 'Телефон' },
      { key: 'raw_address', label: 'Адреса' },
      { key: 'raw_admission_date', label: 'Дата госпіталізації' },
      { key: 'raw_discharge_date', label: 'Дата виписки' },
      { key: 'raw_admission_type', label: 'Тип госпіталізації (Екстренна/Планова)' },
      { key: 'raw_admission_department', label: 'Відділення госпіталізації' },
      { key: 'raw_current_department', label: 'Поточне відділення' },
      { key: 'raw_discharge_department', label: 'Відділення виписки' },
      { key: 'raw_icd_admission', label: 'МКХ-10 при госпіталізації' },
      { key: 'raw_icd_primary', label: 'МКХ-10 основний діагноз' },
      { key: 'raw_doc_name', label: 'Лікар (ПІБ)' },
      { key: 'raw_discharge_status', label: 'Статус виписки' },
      { key: 'raw_operation', label: 'Операція' },
      { key: 'raw_referral', label: 'Направлення' },
      { key: 'raw_referral_status', label: 'Статус направлення' },
    ],
  },
  patients_best: {
    label: 'Пацієнти (patients_best)',
    staging: 'patients_import_staging',
    target: 'patients_best',
    fields: [
      { key: 'raw_full_name', label: 'ПІБ повністю' },
      { key: 'raw_patient_name', label: 'Прізвище' },
      { key: 'raw_patient_prename', label: "Ім'я" },
      { key: 'raw_parental', label: 'По батькові' },
      { key: 'raw_gender', label: 'Стать' },
      { key: 'raw_birthday', label: 'Дата народження' },
      { key: 'raw_age', label: 'Вік' },
      { key: 'raw_phone', label: 'Телефон' },
      { key: 'raw_address', label: 'Адреса' },
      { key: 'raw_locality', label: 'Населений пункт' },
      { key: 'raw_city_name', label: 'Місто' },
      { key: 'raw_district', label: 'Район' },
      { key: 'raw_region', label: 'Область' },
      { key: 'raw_nationality', label: 'Громадянство' },
      { key: 'raw_category', label: 'Категорія' },
    ],
  },
  empl: {
    label: 'Співробітники (empl)',
    staging: 'empl_import_staging',
    target: 'empl',
    fields: [
      { key: 'raw_emp_name', label: 'Прізвище' },
      { key: 'raw_full_name', label: 'ПІБ повністю' },
      { key: 'raw_department', label: 'Відділення' },
      { key: 'raw_specialization', label: 'Спеціалізація' },
      { key: 'raw_position', label: 'Посада' },
      { key: 'raw_gender', label: 'Стать' },
      { key: 'raw_birthday', label: 'Дата народження' },
      { key: 'raw_phone', label: 'Телефон' },
      { key: 'raw_email', label: 'Email' },
      { key: 'raw_taxid', label: 'ІПН' },
      { key: 'raw_status', label: 'Статус' },
    ],
  },
}

export const IMPORT_TABLE_KEYS = Object.keys(IMPORT_TABLES)
